name: number_system
description: A package to extend the functionality to convert between number systems
version: 0.0.4+5
homepage:
repository: https://github.com/LiveUser/number_system

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
  test:
  lints: